### ISSUE TITLE
IBfsPositionService.GetGetHoldingsOverTimeAsync throws exception when Assets is assigned Guid[]

### ISSUE THREAD

**Issue by brantsrasmus** [Bricknode/Bricknode.Soap.Sdk#2]
IBfsPositionService.GetGetHoldingsOverTimeAsync throws an error 

`System.ServiceModel.FaultException: Server was unable to process request. ---> Unable to cast object of type 'System.Guid[]' to type 'System.String[]'.
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at Bricknode.Soap.Sdk.Services.BfsPositionService.GetHoldingsOverTimeAsync(GetHoldingsOverTimeArgs filters)`

When GetHoldingsOverTimeArgs.Assets is a Guid Array. This error is thrown whenever the property is not null. When the Assets property is null, the method works.

**Comment by brantsrasmus** [comment]
`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/">
   <soap:Header/>
   <soap:Body>
      <tem:GetHoldingsOverTime>
         
         <tem:req>
            
            <tem:Credentials>
               
               <tem:UserName>***</tem:UserName>
               
               <tem:Password>***</tem:Password>
            </tem:Credentials>
            
            <tem:identify>***</tem:identify>
            
            <tem:Args>
               <tem:Start>2020-01-01</tem:Start>
               <tem:End>2020-01-01</tem:End>
               
               <tem:DisplayCurrencyCode>SEK</tem:DisplayCurrencyCode>
               
               <tem:Accounts>
                  
                  <tem:guid>52134d09-5c00-4357-a62f-02f10ac4d339</tem:guid>
               </tem:Accounts>
               
               <tem:Assets>
                  
                  <tem:guid>cbda471b-26c2-4a6c-b5d9-cf7a800c185e</tem:guid>
               </tem:Assets>
            </tem:Args>
            <tem:Fields></tem:Fields>
            
         </tem:req>
      </tem:GetHoldingsOverTime>
   </soap:Body>
</soap:Envelope>`

`<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">Server was unable to process request. ---> Unable to cast object of type 'System.Guid[]' to type 'System.String[]'.</soap:Text>
         </soap:Reason>
         <soap:Detail/>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>`

**Comment by brantsrasmus** [comment]
Closing since you implemented a hotfix resolving this issue
